"""esquema inicial

Revision ID: 6b49f74b1b35
Revises: 
Create Date: 2026-07-28 15:29:46.956251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b49f74b1b35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_number')
    )
    op.create_table('movement_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('report_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('branch_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('identifier_type', sa.String(length=20), nullable=False),
    sa.Column('regex_pattern', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['movement_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('unclassified_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('description_original', sa.String(length=500), nullable=False),
    sa.Column('reference_original', sa.String(length=255), nullable=True),
    sa.Column('normalized_text', sa.String(length=500), nullable=False),
    sa.Column('external_folio', sa.String(length=100), nullable=True),
    sa.Column('charge_cents', sa.Integer(), nullable=False),
    sa.Column('payment_cents', sa.Integer(), nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=True),
    sa.Column('movement_hash', sa.String(length=64), nullable=False),
    sa.Column('occurrence_number', sa.Integer(), nullable=False),
    sa.Column('classification_status', sa.String(length=15), nullable=False),
    sa.Column('classification_method', sa.String(length=20), nullable=False),
    sa.Column('matched_identifier', sa.String(length=100), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['movement_categories.id'], ),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_hash', 'occurrence_number', name='uq_movement_hash_occurrence')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index('ix_movements_account', ['bank_account_id'], unique=False)
        batch_op.create_index('ix_movements_branch', ['branch_id'], unique=False)
        batch_op.create_index('ix_movements_category', ['category_id'], unique=False)
        batch_op.create_index('ix_movements_classification_status', ['classification_status'], unique=False)
        batch_op.create_index('ix_movements_date', ['movement_date'], unique=False)

    op.create_table('movement_classification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('previous_branch_id', sa.Integer(), nullable=True),
    sa.Column('new_branch_id', sa.Integer(), nullable=True),
    sa.Column('previous_category_id', sa.Integer(), nullable=True),
    sa.Column('new_category_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('create_rule', sa.Boolean(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['new_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['new_category_id'], ['movement_categories.id'], ),
    sa.ForeignKeyConstraint(['previous_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['previous_category_id'], ['movement_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_classification_history')
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index('ix_movements_date')
        batch_op.drop_index('ix_movements_classification_status')
        batch_op.drop_index('ix_movements_category')
        batch_op.drop_index('ix_movements_branch')
        batch_op.drop_index('ix_movements_account')

    op.drop_table('movements')
    op.drop_table('imported_files')
    op.drop_table('classification_rules')
    op.drop_table('branch_identifiers')
    op.drop_table('bank_accounts')
    op.drop_table('movement_categories')
    op.drop_table('branches')
    op.drop_table('banks')
    # ### end Alembic commands ###
